### ISSUE TITLE
manage links with fake OS pid without an error

### ISSUE THREAD

**Issue by Timrael** [saleyn/erlexec#51] opened 2015-08-25 10:43 UTC
Hello Sergei,

I have an issue with passing fake OS pid to manage function:

```erlang
FakeOsPid = 12345.
exec:manage(FakeOsPid, []).
```

I expect 'error', but always got 'ok'.

**Comment by saleyn** [comment] 2015-08-26 14:19
This issue has been fixed in the latest commit.

**Closed by saleyn** 2015-08-26 14:19 UTC

**Comment by Timrael** [comment] 2015-08-27 08:24
Thanks! You're doing a good job.

**Comment by Timrael** [comment] 2015-09-28 07:23
@saleyn sorry man, but now exec:manage returns {error, not_found} for all pids, no matter it's real or not.

**Comment by saleyn** [comment] 2015-09-29 21:06
I can't reproduce your issue:
```
$ sleep 2000
$ ps aux | grep sleep
serge    12834  0.0  0.0   5800   760 pts/3    S+   17:00   0:00 sleep 2000
$ erl
$ exec:start().
{ok,<0.36.0>}
2> exec:manage(12834, []).
{ok,<0.38.0>,12834}
```

**Comment by saleyn** [comment] 2015-09-29 21:14
Apparently the Linux API call I used wasn't correct. The issue is fixed now.
